export { basicSetup, EditorView } from "codemirror";
export { EditorState, Compartment } from "@codemirror/state";
export { keymap } from "@codemirror/view";
export { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
export { tags } from "@lezer/highlight";
export { javascript } from "@codemirror/lang-javascript";
export { python } from "@codemirror/lang-python";
export { rust } from "@codemirror/lang-rust";
export { html } from "@codemirror/lang-html";
export { css } from "@codemirror/lang-css";
export { json } from "@codemirror/lang-json";
export { markdown } from "@codemirror/lang-markdown";
export { sql } from "@codemirror/lang-sql";
export { yaml } from "@codemirror/lang-yaml";
export { xml } from "@codemirror/lang-xml";
export { StreamLanguage } from "@codemirror/language";
export { shell } from "@codemirror/legacy-modes/mode/shell";
export { toml } from "@codemirror/legacy-modes/mode/toml";
export { dockerFile } from "@codemirror/legacy-modes/mode/dockerfile";
