export function createUiState() {
  return {
    snapshot: null,
    mountedWorkspaceId: null,
    mountedLayoutSignature: null,
    appliedThemeId: null,
    appliedInterfaceTextScale: null,
    appliedTerminalFontSize: null,
    settingsDraft: null,
    launcherVisible: false,
    settingsVisible: false,
    settingsSection: "workbench",
    activePaneId: null,
    pendingWorkspaceDraft: null,
    launcherCommandValue: "",
    launcherHistory: [],
    launcherLatestCard: {
      current: null,
      previous: null,
      phase: "idle",
    },
    launcherCommands: [],
    launcherCommandCursor: null,
    contextMenu: null,
    maximizedPaneId: null,
    gitPanelVisible: false,
    sourceControl: {
      snapshot: null,
      activeTab: "changes",
      selectedPath: "",
      selectedDiffMode: "working-tree",
      diff: null,
      diffLoading: false,
      selectedCommitOid: "",
      commitDetail: null,
      commitDetailLoading: false,
      graphLoadingMore: false,
      createBranchName: "",
      createBranchStartPoint: "",
      commitMessage: "",
      branchSearch: "",
      taskInput: "",
      submitting: false,
      lastLoadedWorkspaceId: "",
    },
    quickSwitcherVisible: false,
    quickSwitcherQuery: "",
    quickSwitcherCursor: 0,
    quickSwitcherShouldFocus: false,
    activityRailVisible: false,
    activityRailScope: "all",
    workspaceRenameDraft: null,
    workspaceRenameShouldFocus: false,
    workspaceRenameSaving: false,
    workspaceTabsScrollLeft: 0,
    workspaceTabsLastActiveWorkspaceId: null,
    workspaceTabsLastCount: 0,
    runtimeActivity: [],
    runtimeAttentionByWorkspace: new Map(),
  };
}

export function createRuntimeStore() {
  return {
    paneTerminals: new Map(),
    pendingTerminalData: new Map(),
    workspacePaneIds: new Map(),
    workspaceScreens: new Map(),
    terminalViewportLines: new Map(),
    visibleTerminalRefreshFrame: 0,
    launcherCardTransitionTimer: 0,
    launcherCardAnimationFrame: 0,
    gitRefreshIntervalTimer: 0,
    gitRefreshInFlight: null,
    gitRefreshQueuedWorkspaceId: null,
  };
}
