export function createUiState() {
  return {
    snapshot: null,
    mountedWorkspaceId: null,
    mountedLayoutSignature: null,
    appliedThemeId: null,
    appliedInterfaceTextScale: null,
    appliedTerminalFontSize: null,
    settingsDraft: null,
    launcherVisible: false,
    settingsVisible: false,
    settingsSection: "workbench",
    activePaneId: null,
    dragHoverPaneId: null,
    pendingWorkspaceDraft: null,
    launcherCommandValue: "",
    launcherHistory: [],
    launcherLatestCard: {
      current: null,
      previous: null,
      phase: "idle",
    },
    launcherCommands: [],
    launcherCommandCursor: null,
    contextMenu: null,
    maximizedPaneId: null,
    gitPanelVisible: false,
    todoPanelVisible: false,
    workspaceTodos: {
      draft: "",
      editTodoId: "",
      editDraft: "",
      completedCollapsed: true,
      shouldFocusCreate: false,
      shouldFocusEditTodoId: "",
      submitting: false,
    },
    sourceControl: {
      snapshot: null,
      activeTab: "changes",
      activeRowMenuKey: "",
      selectedPath: "",
      selectedDiffMode: "working-tree",
      diff: null,
      diffLoading: false,
      selectedCommitOid: "",
      commitDetail: null,
      commitDetailLoading: false,
      graphLoadingMore: false,
      createBranchName: "",
      createBranchStartPoint: "",
      commitMessage: "",
      generatingCommitMessage: false,
      branchSearch: "",
      taskInput: "",
      taskTrayExpanded: false,
      publishModalVisible: false,
      publishModalBranchName: "",
      publishModalRemotes: [],
      publishModalSelectedRemote: "",
      publishModalShouldFocus: false,
      submitting: false,
      lastLoadedWorkspaceId: "",
    },
    quickSwitcherVisible: false,
    quickSwitcherQuery: "",
    quickSwitcherCursor: 0,
    quickSwitcherShouldFocus: false,
    systemHealthPanelVisible: false,
    systemHealthSnapshot: null,
    systemHealthLoading: false,
    systemHealthError: "",
    codexModalVisible: false,
    codexSessionsSnapshot: null,
    codexSessionsLoading: false,
    codexSessionsError: "",
    codexSelectedSessionId: "",
    codexTargetPaneId: null,
    codexSubmitting: false,
    codexShouldFocus: false,
    activityRailVisible: false,
    activityRailScope: "all",
    workspaceRenameDraft: null,
    workspaceRenameShouldFocus: false,
    workspaceRenameSaving: false,
    workspaceTabDrag: null,
    workspaceTabSuppressClickUntil: 0,
    workspaceTabSuppressClickWorkspaceId: "",
    workspaceTabsScrollLeft: 0,
    workspaceTabsLastActiveWorkspaceId: null,
    workspaceTabsLastCount: 0,
    runtimeActivity: [],
    runtimeAttentionByWorkspace: new Map(),
  };
}

export function createRuntimeStore() {
  return {
    paneTerminals: new Map(),
    pendingTerminalData: new Map(),
    workspacePaneIds: new Map(),
    workspaceScreens: new Map(),
    terminalViewportLines: new Map(),
    visibleTerminalRefreshFrame: 0,
    browserHandledDropPaneId: null,
    browserHandledDropAt: 0,
    workspaceTabAutoScrollFrame: 0,
    launcherCardTransitionTimer: 0,
    launcherCardAnimationFrame: 0,
    gitRefreshInFlight: null,
    gitRefreshQueuedWorkspaceId: null,
    systemHealthRefreshTimer: 0,
    systemHealthRefreshMode: "",
    systemHealthRefreshInFlight: null,
    pendingRenderMask: 0,
    pendingRenderFrame: 0,
    renderMetrics: {
      flushCount: 0,
      lastMask: 0,
      regionFlushCounts: {
        strip: 0,
        stage: 0,
        status: 0,
        activity: 0,
        modal: 0,
        context: 0,
        terminals: 0,
      },
    },
  };
}
